version: '3.8'
services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    restart: always
    ports:
      - 3005:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    deploy:
      replicas: 1
      restart_policy:
        condition: any

volumes:
  todo-mysql-data: